# Generated by Django 5.1.4 on 2024-12-09 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hubmembership',
            unique_together={('user', 'hub')},
        ),
    ]
