# Generated by Django 5.1.4 on 2024-12-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
