# Generated by Django 5.1.4 on 2024-12-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_hubchatgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HubChatGroup',
            new_name='HubChannel',
        ),
    ]
