# Generated by Django 5.1.4 on 2024-12-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_remove_message_hub_hubchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubchannel',
            name='hub',
        ),
    ]
