# Generated by Django 5.1.4 on 2024-12-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_rename_hubchatgroup_hubchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hubChatGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.hubchannel'),
            preserve_default=False,
        ),
    ]
