# Generated by Django 5.1.4 on 2024-12-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_hubchannel_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hubChannels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.hubchannel'),
            preserve_default=False,
        ),
    ]
