# Generated by Django 5.1.4 on 2024-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_message_hubchannels'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
